### ISSUE TITLE
hi im having a problem where my MC keep crashing 

### ISSUE THREAD

**Issue by alex0205** [McJty/McJtyLib#111]
hi my mc keep crashing when i have rftool and mcjtylib installed i determine that this is causing my mc to crash when i go and start up. before when i didnt have these 2 mod install my mc would run perfectly fine. i even downgrade to the previous version and it still crash im not sure why my mc is crashing but can you please help me out. here the crash report

Time: 1/2/20 1:53 PM
Description: Initializing game

java.lang.NoClassDefFoundError: Lmcjty/rftools/proxy/CommonProxy;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredField(Unknown Source)
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:70)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:611)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: mcjty.rftools.proxy.CommonProxy
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 48 more
Caused by: java.lang.NoClassDefFoundError: mcjty/lib/proxy/AbstractCommonProxy
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 50 more
Caused by: java.lang.ClassNotFoundException: mcjty.lib.proxy.AbstractCommonProxy
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 54 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredField(Unknown Source)
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:70)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:611)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1523629680 bytes (1453 MB) / 2017460224 bytes (1924 MB) up to 22429564928 bytes (21390 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx24064m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2846 Optifine OptiFine_1.12.2_HD_U_E3 56 mods loaded, 56 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version                  | Source                                            | Signature                                |
	|:----- |:------------------------ |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                | 1.12.2                   | minecraft.jar                                     | None                                     |
	| LC    | mcp                      | 9.42                     | minecraft.jar                                     | None                                     |
	| LC    | FML                      | 8.0.99.99                | forge-1.12.2-14.23.5.2846-universal.jar           | None                                     |
	| LC    | forge                    | 14.23.5.2846             | forge-1.12.2-14.23.5.2846-universal.jar           | None                                     |
	| LC    | actuallyadditions        | 1.12.2-r149              | ActuallyAdditions-1.12.2-r149.jar                 | None                                     |
	| LC    | applecore                | 3.1.0                    | AppleCore-mc1.12.2-3.1.0.jar                      | None                                     |
	| LC    | crafttweaker             | 4.1.17                   | CraftTweaker2-1.12-4.1.17.jar                     | None                                     |
	| LC    | mtlib                    | 3.0.6                    | MTLib-3.0.6.jar                                   | None                                     |
	| LC    | modtweaker               | 4.0.17                   | modtweaker-4.0.17.jar                             | None                                     |
	| LC    | jei                      | 4.15.0.287               | jei_1.12.2-4.15.0.287.jar                         | None                                     |
	| LC    | appleskin                | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
	| LC    | chameleon                | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| LC    | codechickenlib           | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux             | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal (1).jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | cofhcore                 | 4.6.2                    | CoFHCore-1.12.2-4.6.2.25-universal.jar            | None                                     |
	| LC    | cofhworld                | 1.3.0                    | CoFHWorld-1.12.2-1.3.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | cyclopscore              | 1.6.0                    | CyclopsCore-1.12.2-1.6.0.jar                      | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LC    | commoncapabilities       | 2.4.5                    | CommonCapabilities-1.12.2-2.4.5.jar               | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LC    | ctgui                    | 1.0.0                    | CraftTweaker2-1.12-4.1.17.jar                     | None                                     |
	| LC    | crafttweakerjei          | 2.0.3                    | CraftTweaker2-1.12-4.1.17.jar                     | None                                     |
	| LC    | forgelin                 | 1.8.2                    | Forgelin-1.8.2.jar                                | None                                     |
	| LC    | mantle                   | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                          | None                                     |
	| LC    | tconstruct               | 1.12.2-2.12.0.135        | TConstruct-1.12.2-2.12.0.135.jar                  | None                                     |
	| LC    | exnihilocreatio          | 1.12.2-0.4.4             | exnihilocreatio-1.12.2-0.4.4.jar                  | None                                     |
	| LC    | excompressum             | 3.0.27                   | ExCompressum_1.12.2-3.0.27.jar                    | None                                     |
	| LC    | extrautils2              | 1.0                      | extrautils2-1.12-1.9.9.jar                        | None                                     |
	| LC    | ftblib                   | 5.4.1.97                 | FTBLib-5.4.1.97.jar                               | None                                     |
	| LC    | ftbutilities             | 5.4.0.95                 | FTBUtilities-5.4.0.95.jar                         | None                                     |
	| LC    | headcrumbs               | 2.0.4                    | Headcrumbs-1.12.2-2.0.5.17.jar                    | None                                     |
	| LC    | waila                    | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2 (1).jar                   | None                                     |
	| LC    | integrateddynamics       | 1.1.1                    | IntegratedDynamics-1.12.2-1.1.1.jar               | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LC    | integrateddynamicscompat | 1.0.0                    | IntegratedDynamics-1.12.2-1.1.1.jar               | None                                     |
	| LC    | inventorytweaks          | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | journeymap               | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                       | None                                     |
	| LC    | mcjtylib_ng              | 3.5.4                    | mcjtylib-1.12-3.5.4.jar                           | None                                     |
	| LC    | mousetweaks              | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                     | None                                     |
	| LC    | neat                     | 1.4-17                   | Neat+1.4-17.jar                                   | None                                     |
	| LC    | nei                      | 2.4.2                    | NotEnoughItems-1.12.2-2.4.2.240-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | oreexcavation            | 1.4.140                  | OreExcavation-1.4.140.jar                         | None                                     |
	| LC    | thermalfoundation        | 2.6.2                    | ThermalFoundation-1.12.2-2.6.2.26-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalexpansion         | 5.5.3                    | ThermalExpansion-1.12.2-5.5.3.41-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermaldynamics          | 2.5.4                    | ThermalDynamics-1.12.2-2.5.4.18-universal (1).jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | simplyjetpacks           | 2.2.11.64                | SimplyJetpacks2-1.12.2-2.2.11.64.jar              | None                                     |
	| LC    | plustic                  | 7.0.6.1                  | plustic-7.0.6.1.jar                               | None                                     |
	| LC    | randomthings             | 4.2.6                    | RandomThings-MC1.12.2-4.2.6.jar                   | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LC    | refinedstorage           | 1.6.14                   | refinedstorage-1.6.14.jar                         | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| L     | rftools                  | 7.61                     | rftools-1.12-7.61.jar                             | None                                     |
	| L     | storagedrawers           | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                   | None                                     |
	| L     | tinkertoolleveling       | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar               | None                                     |
	| L     | tp                       | 3.2.25                   | tinyprogressions-1.12.2-3.3.25-Release.jar        | None                                     |
	| L     | veinminer                | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a (2).jar         | None                                     |
	| L     | veinminermodsupport      | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a (2).jar         | None                                     |
	| L     | wailaharvestability      | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar             | None                                     |
	| L     | wawla                    | 2.5.273                  | Wawla-1.12.2-2.5.273.jar                          | None                                     |
	| L     | xnet                     | 1.8.2                    | xnet-1.12-1.8.2.jar                               | None                                     |
	| L     | immersiveengineering     | 0.12-89                  | ImmersiveEngineering-0.12-89.jar                  | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (RandomThings-MC1.12.2-4.2.6.jar)
  lumien.randomthings.asm.ClassTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
AppleCore (AppleCore-mc1.12.2-3.1.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 436.02' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 436.02, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 436.02
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
[13:53:37] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\acz91\Desktop\MultiMC\instances\newew\.minecraft\crash-reports\crash-2020-01-02_13.53.36-client.txt
Process exited with code -1.
MultiMC: Log upload triggered at: 02 Jan 2020 14:16:21 -0600

**Comment by josephcsible** [comment]
See if updating to RFTools 7.72 fixes it.

**Comment by alex0205** [comment]
okay thank ill give this a try now
