### ISSUE TITLE
1.16.3 crash on tick: NullPointerException in BaseBlock -> OrientationTools

### ISSUE THREAD

**Issue by andrewsf** [McJty/McJtyLib#125]
# Versions
* Forge:  34.1.25
* mcjtylib: 1.16-5.0.11
* rftoolsbase: 1.16-2.0.6
* rftoolsbuilder: 1.16-3.0.8
* rftoolscontrol: 1.16-4.0.5
* rftoolspower: 1.16-3.0.8
* rftoolsstorage: 1.16-2.0.5
* rftoolsutility: 1.16-3.0.11
* botania:  1.16.3-409

```
[23:00:47] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:80) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$22319/1428006496.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at mcjty.lib.varia.OrientationTools.getFacingFromEntity(OrientationTools.java:139) ~[?:1.16-5.0.11]
	at mcjty.lib.blocks.BaseBlock.func_196258_a(BaseBlock.java:411) ~[?:1.16-5.0.11]
	at net.minecraft.item.BlockItem.func_195945_b(BlockItem.java:105) ~[?:?]
	at net.minecraft.item.BlockItem.redirect$zcj000$alterPlacementState(BlockItem.java:1024) ~[?:?]
	at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:51) ~[?:?]
	at vazkii.botania.common.block.subtile.functional.SubTileRannuncarpus.tickFlower(SubTileRannuncarpus.java:98) ~[?:1.16.3-409]
	at vazkii.botania.api.subtile.TileEntitySpecialFlower.func_73660_a(TileEntitySpecialFlower.java:113) ~[?:1.16.3-409]
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:366) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:847) ~[?:?]
	... 6 more
```

# Cause
Thrown by [OrientationTools.java:139](https://github.com/McJtyMods/McJtyLib/blob/81cbd496293cc8bb051f9d876b8ee133c9755071/src/main/java/mcjty/lib/varia/OrientationTools.java#L139). `entityIn` is null:

```
if (MathHelper.abs((float) entityIn.getPosX() - clickedBlock.getX()) < 2.0F && MathHelper.abs((float) entityIn.getPosZ() - clickedBlock.getZ()) < 2.0F) {
```

... because `PlayerEntity placer = context.getPlayer()` is null at [BaseBlock.java:400](https://github.com/McJtyMods/McJtyLib/blob/81cbd496293cc8bb051f9d876b8ee133c9755071/src/main/java/mcjty/lib/blocks/BaseBlock.java#L400):
 
```
PlayerEntity placer = context.getPlayer();

/* ... */

case ROTATION:
    return state.with(BlockStateProperties.FACING, OrientationTools.getFacingFromEntity(pos, placer));
```

[`BlockItemUseContext`](https://forge.yue.moe/javadoc/1.16.3/net/minecraft/item/BlockItemUseContext.html) inherits [`ItemUseContext#getPlayer`, which is marked `@Nullable`](https://forge.yue.moe/javadoc/1.16.3/net/minecraft/item/ItemUseContext.html#getPlayer--).

Occurred when I dropped a Crafter `rftoolsutility:crafter2` on the ground near a Rannuncarpus `botania:rannuncarpus` from Botania.
Now the game crashes when loading the world.

**Comment by McJty** [comment]
What is a Rannuncarpus?

**Comment by andrewsf** [comment]
[Botania](https://botaniamod.net/) is a mod, and [Rannuncarpus](https://ftb.gamepedia.com/Rannuncarpus) is a block from that mod.
But based on the Javadoc, I'm sure there are many places where `getPlayer()` can return null, without Botania?

**Comment by andrewsf** [comment]
The code setting up the null player is here: [SubTileRannuncarpus.java:212](https://github.com/Vazkii/Botania/blob/b708657d9fe2f9b0363d19ff794481414bbc5443/src/main/java/vazkii/botania/common/block/subtile/functional/SubTileRannuncarpus.java#L212)

```
	// BlockItemUseContext uses a nullable player field without checking it -.-
	private static class RannuncarpusPlaceContext extends BlockItemUseContext {

/* ... */

		public RannuncarpusPlaceContext(World world, ItemStack stack, BlockRayTraceResult rtr, BlockPos flowerPos) {
			super(world, null, Hand.MAIN_HAND, stack, rtr);
```

A comment on the class suggests McJtyLib is not the only user of `getPlayer()` that doesn't do a null check.

**Comment by McJty** [comment]
There are usually not many places where getPlayer() can be null. And while I agree that this is a bug on my part for not checking that (a bug that I will fixed) I feel that it would be safer for Botania to at least pass along a fake player to avoid this problem. But I'll fix this for next release
