### ISSUE TITLE
[1.16.5]Clinet

### ISSUE THREAD

**Issue by ljt1477059273** [McJty/McJtyLib#132]
``---- Minecraft Crash Report ----
// My bad.

Time: 21-5-8 下午4:04
Description: Tesselating block model

java.lang.IllegalStateException: not enough data
	at net.minecraftforge.client.model.pipeline.BakedQuadBuilder.build(BakedQuadBuilder.java:124) ~[forge:?] {re:classloading}
	at mcjty.lib.client.AbstractDynamicBakedModel.createQuad(AbstractDynamicBakedModel.java:105) ~[mcjtylib:1.16-5.0.19] {re:classloading}
	at mcjty.xnet.modules.cables.client.GenericCableBakedModel.getQuads(GenericCableBakedModel.java:174) ~[xnet:1.16-3.0.11] {re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:154) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:89) ~[forge:?] {re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:101) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:83) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:907) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:734) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$1(ChunkRenderDispatcher.java:191) ~[?:?] {re:classloading,xf:OptiFine:default}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) ~[?:1.8.0_281] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) ~[?:1.8.0_281] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_281] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1646) ~[?:1.8.0_281] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_281] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_281] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) ~[?:1.8.0_281] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) ~[?:1.8.0_281] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) ~[?:1.8.0_281] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.client.model.pipeline.BakedQuadBuilder.build(BakedQuadBuilder.java:124) ~[forge:?] {re:classloading}
	at mcjty.lib.client.AbstractDynamicBakedModel.createQuad(AbstractDynamicBakedModel.java:105) ~[mcjtylib:1.16-5.0.19] {re:classloading}
	at mcjty.xnet.modules.cables.client.GenericCableBakedModel.getQuads(GenericCableBakedModel.java:174) ~[xnet:1.16-3.0.11] {re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:154) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:89) ~[forge:?] {re:classloading}
-- Block model being tesselated --
Details:
	Block: Block{xnet:netcable}[color=red,down=cable,east=none,north=none,south=none,up=cable,west=none]
	Block location: World: (412,64,-430), Chunk: (at 12,4,2 in 25,-27; contains blocks 400,0,-432 to 415,255,-417), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:101) ~[?:?] {re:classloading,xf:OptiFine:default}

-- Block being tesselated --
Details:
	Block: Block{xnet:netcable}[color=red,down=cable,east=none,north=none,south=none,up=cable,west=none]
	Block location: World: (412,64,-430), Chunk: (at 12,4,2 in 25,-27; contains blocks 400,0,-432 to 415,255,-417), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:83) ~[?:?] {re:classloading,xf:OptiFine:default}

-- Affected level --
Details:
	All players: 2 total; [ClientPlayerEntity['MTong_huahua'/642, l='ClientLevel', x=304.36, y=64.88, z=-350.56], RemoteClientPlayerEntity['Sang_leaf'/186, l='ClientLevel', x=329.66, y=64.00, z=-321.23]]
	Chunk stats: Client Chunk Cache: 361, 246
	Level dimension: minecraft:overworld
	Level spawn location: World: (196,66,-367), Chunk: (at 4,4,1 in 12,-23; contains blocks 192,0,-368 to 207,255,-353), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 9468819 game time, 10159746 day time
	Server brand: LoliServer
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$3(ChunkRenderDispatcher.java:197) ~[?:?] {re:classloading,xf:OptiFine:default}
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) ~[?:1.8.0_281] {}
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) ~[?:1.8.0_281] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_281] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1646) ~[?:1.8.0_281] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_281] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_281] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) ~[?:1.8.0_281] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) ~[?:1.8.0_281] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) ~[?:1.8.0_281] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5479186720 bytes (5225 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 16
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/%5BC-光影%5DOptiFine_1.16.5_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.4.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.4
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		[C-背包整理]inventoryprofiles-forge-1.16.2-0.4.2.jar  |Inventory Profiles            |inventoryprofiles             |0.4.2               |DONE      |NOSIGNATURE
		[地洞山崖]CC(FG1.16.4)+v1.1.4.jar                     |Caves And Cliffs              |caves_and_cliffs              |1.1.4               |DONE      |NOSIGNATURE
		[C-JEI]jei-1.16.5-7.6.4.87.jar                    |Just Enough Items             |jei                           |7.6.4.87            |DONE      |NOSIGNATURE
		[中式工坊]ChineseWorkshop-1.16.3-3.2.1.jar            |ChineseWorkshop               |chineseworkshop               |3.2.1               |DONE      |NOSIGNATURE
		[中式工坊-前置]Kiwi-1.16.5-3.5.0.jar                    |Kiwi                          |kiwi                          |3.5.0               |DONE      |NOSIGNATURE
		[Macaw-窗户]mcw-windows-1.0.3-mc1.16.5.jar          |Macaw's Windows               |mcwwindows                    |1.0.3               |DONE      |NOSIGNATURE
		[更好地破坏半砖]KleeSlabs_1.16.5-9.2.1.jar               |KleeSlabs                     |kleeslabs                     |9.2.1               |DONE      |NOSIGNATURE
		[YUNG-洞穴优化]BetterCaves-Forge-1.16.4-1.1.1.jar     |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.1        |DONE      |NOSIGNATURE
		[高级钩爪发射器-前置]ForgeEndertech-1.16.4-7.1.0.0-build.00|Forge Endertech               |forgeendertech                |7.1.0.0             |DONE      |NOSIGNATURE
		[传送石碑]Waystones_1.16.5-7.4.0.jar                  |Waystones                     |waystones                     |7.4.0               |DONE      |NOSIGNATURE
		[更好的标题页]BetterTitleScreen-1.16.4-1.10.2.jar       |Better Title Screen           |bettertitlescreen             |1.16.4-1.10.2       |DONE      |NOSIGNATURE
		[懒人厨房]CookingForBlockheads_1.16.5-9.3.1.jar       |Cooking for Blockheads        |cookingforblockheads          |9.3.1               |DONE      |NOSIGNATURE
		[C-旅行地图]journeymap-1.16.5-5.7.1.jar               |Journeymap                    |journeymap                    |5.7.1               |DONE      |NOSIGNATURE
		[神化-前置]Placebo-1.16.4-4.4.2.jar                   |Placebo                       |placebo                       |4.4.2               |DONE      |NOSIGNATURE
		[C-自动汉化]i18nupdatemod-1.16.5-2.0.1.jar            |I18n update Mod               |i18nupdatemod                 |2.0.1               |DONE      |NOSIGNATURE
		[旅行者背包]TravelersBackpack-1.16.5-5.4.1.jar         |Traveler's Backpack           |travelersbackpack             |5.4.1               |DONE      |NOSIGNATURE
		[YUNG-洞穴优化-前置]YungsApi-1.16.4-Forge-6.jar         |YUNG's API                    |yungsapi                      |1.16.4-Forge-6      |DONE      |NOSIGNATURE
		[高级钩爪发射器]AdHooks-1.16.4-6.1.4.0-build.0110.jar    |Advanced Hook Launchers       |adhooks                       |6.1.4.0             |DONE      |NOSIGNATURE
		[冠军]champions-forge-1.16.5-2.0.1.5.jar            |Champions                     |champions                     |1.16.5-2.0.1.5      |DONE      |NOSIGNATURE
		[生物黑名单]BadMobs-1.16.5-9.0.3.jar                   |BadMobs                       |badmobs                       |9.0.3               |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		[神化]Apotheosis-1.16.4-4.5.2.jar                   |Apotheosis                    |apotheosis                    |4.5.2               |DONE      |NOSIGNATURE
		[物流管道-前置]mcjtylib-1.16-5.0.19.jar                 |McJtyLib                      |mcjtylib                      |1.16-5.0.19         |DONE      |NOSIGNATURE
		[物流管道-前置]rftoolsbase-1.16-2.0.10.jar              |RFToolsBase                   |rftoolsbase                   |1.16-2.0.10         |DONE      |NOSIGNATURE
		[物流管道]xnet-1.16-3.0.11.jar                        |XNet                          |xnet                          |1.16-3.0.11         |DONE      |NOSIGNATURE
		[Macaw-门]mcw-doors-1.0.2-mc1.16.5.jar             |Macaw's Doors                 |mcwdoors                      |1.0.2               |DONE      |NOSIGNATURE
		[道路2-前置]mapperbase-1.16.4-2.3.0.0.jar             |Mapper Base                   |mapperbase                    |1.16.4-2.3.0.0      |DONE      |NOSIGNATURE
		[搬运]carryon-1.16.5-1.15.3.13.jar                  |Carry On                      |carryon                       |1.15.3.13           |DONE      |8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		[C-JEI-附属]JustEnoughResources-1.16.4-0.12.0.109.ja|Just Enough Resources         |jeresources                   |0.12.0.109          |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.4-universal.jar                 |Forge                         |forge                         |36.1.4              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		[更多箱子]ironchest-1.16.4-11.2.10.jar                |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.4-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		[工业先锋]industrial-foregoing-1.16.5-3.2.11-55cb112.j|Industrial Foregoing          |industrialforegoing           |3.2.11              |DONE      |NOSIGNATURE
		[农夫乐事]FarmersDelight-1.16.3-0.4.1.jar             |Farmer's Delight              |farmersdelight                |1.16.3-0.4.1        |DONE      |NOSIGNATURE
		[Macaw-桥梁]mcw-bridges-1.0.5-mc1.16.5-4.jar        |Macaw's Bridges               |mcwbridges                    |1.0.5               |DONE      |NOSIGNATURE
		[围火无怪]nohostilesaroundcampfire_1.16.5-3.3.jar     |No Hostiles Around Campfire   |nohostilesaroundcampfire      |3.3                 |DONE      |NOSIGNATURE
		[C-鼠标手势]MouseTweaks-2.14-mc1.16.2.jar             |Mouse Tweaks                  |mousetweaks                   |2.14                |DONE      |NOSIGNATURE
		[工业先锋-前置]titanium-1.16.5-3.2.8.2.jar              |Titanium                      |titanium                      |3.2.8.2             |DONE      |NOSIGNATURE
		[超多生物群系]BiomesOPlenty-1.16.5-13.1.0.458-universal.|Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.439   |DONE      |NOSIGNATURE
		[C-玉-高亮显示]Jade-1.16.4-2.6.2.jar                   |Jade                          |jade                          |2.6.2               |DONE      |NOSIGNATURE
		[C-实体渲染机制优化]EntityCulling-1.16.5-2.1.3.jar        |Entity Culling                |entity_culling                |2.1.3               |DONE      |NOSIGNATURE
		[Macaw-活板门]mcw-trapdoors-1.0.2-mc1.16.5.jar       |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.2               |DONE      |NOSIGNATURE
		[点歌][forge-1.16.2]AllMusic-2.3.0(hotfix).jar      |AllMusic                      |allmusic                      |2.3.0               |DONE      |NOSIGNATURE
		[C-流畅加载]smoothboot-forge-1.16.4-1.2.2.jar         |Smooth Boot                   |smoothboot                    |1.16.4-1.2.2        |DONE      |NOSIGNATURE
		[圣诞彩灯]fairylights-4.0.5-1.16.5.jar                |Fairy Lights                  |fairylights                   |4.0.5               |DONE      |NOSIGNATURE
		[C-JEI-附属]jeiintegration_1.16.5-7.0.1.15.jar      |JEI Integration               |jeiintegration                |7.0.1.15            |DONE      |NOSIGNATURE
		[帕秋莉手册]Patchouli-1.16.4-50.jar                    |Patchouli                     |patchouli                     |1.16.4-50           |DONE      |NOSIGNATURE
		[围火无怪-前置]collective-1.16.5-2.26.jar               |Collective                    |collective                    |2.26                |DONE      |NOSIGNATURE
		[道路2]roadstuff-1.16.4-4.2.0.jar                   |Road Stuff                    |roadstuff                     |1.16.4-4.2.0        |DONE      |NOSIGNATURE
		[C-JEI-附属-拼音]JustEnoughCharacters-1.16.4-4.1.6.jar|Just Enough Characters        |jecharacters                  |4.1.6               |DONE      |NOSIGNATURE
		[雕像]Statues-1.16.5-0.1.6.8.jar                    |Statues Mod                   |statues                       |0.1.6.8             |DONE      |NOSIGNATURE
		[载具-前置]obfuscate-0.6.0-1.16.3.jar                 |Obfuscate                     |obfuscate                     |0.6.0               |DONE      |e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		[载具]vehicle-mod-0.45.2-1.16.3.jar                 |MrCrayfish's Vehicle Mod      |vehicle                       |0.45.2              |DONE      |NOSIGNATURE
		[YUNG的要塞重制]BetterStrongholds-1.16.4-1.0.1.jar     |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.0.1        |DONE      |NOSIGNATURE
		[建筑工艺]buildersaddition-1.16.5-20210421a.jar       |Builders Crafts & Addition    |buildersaddition              |1.16.5-20210421a    |DONE      |NOSIGNATURE
		[建筑之杖]constructionwand-1.16.5-2.2.jar             |Construction Wand             |constructionwand              |1.16.5-2.2          |DONE      |NOSIGNATURE
		[Macaw-屋顶]mcw-roofs-2.0.1-mc1.16.5-4.jar          |Macaw's Roofs                 |mcwroofs                      |2.0.1               |DONE      |NOSIGNATURE
		[家具]furniture-7.0.0-pre19-1.16.3.jar              |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre19         |DONE      |NOSIGNATURE
		[刷怪场助手]architectury-1.12.145-forge.jar            |Architectury                  |architectury                  |1.12.145            |DONE      |NOSIGNATURE
		[刷怪场助手]MobFarmHelpers-1.16.5-1.4.2-forge.jar      |Mob Farm Helpers              |mobfarmutilities              |1.4.2               |DONE      |NOSIGNATURE
		[Macaw-家具]mcw-furniture-2.0.1-mc1.16.5.jar        |Macaw's Furniture             |mcwfurnitures                 |2.0.1               |DONE      |NOSIGNATURE
		[水产养殖2]Aquaculture-1.16.5-2.1.18.jar              |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.18       |DONE      |NOSIGNATURE
		[YUNG的矿井优化]BetterMineshafts-Forge-1.16.4-2.0.3.jar|YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.3        |DONE      |NOSIGNATURE
		[Thutmose的电梯-前置]thutcore-1.16.4-8.2.0.jar         |Thut Core                     |thutcore                      |8.2.0               |DONE      |NOSIGNATURE
		[Thutmose的电梯]thuttech-1.16.4-9.1.2.jar            |Thut Elevators                |thuttech                      |9.1.2               |DONE      |NOSIGNATURE
	Crash Report UUID: 4e51d5c1-388b-415c-bb05-06a71e351ea1
	Kiwi Modules: 
		chineseworkshop:blocks
		chineseworkshop:debug_stick
		chineseworkshop:decorations
		chineseworkshop:materials
		chineseworkshop:retexture
		kiwi:contributors
		kiwi:data
	Patchouli open book context: n/a
	Launched Version: HMCL 3.3.172
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: ~~ERROR~~ IllegalStateException: Rendersystem called from wrong thread
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, Minecraft-Mod-Language-Modpack-1-16.zip
	Current Language: 简体中文 (中国)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 
	OptiFine Version: OptiFine_1.16.5_HD_U_G7
	OptiFine Build: 20210219-144623
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 461.72
	OpenGlRenderer: GeForce RTX 2060 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by McJty** [comment]
I need more info. When does this happen? Do you also have this problem without optfine?

**Comment by ljt1477059273** [comment]
Yes, it's the same without OptFine. I suddenly break down like this when I run the worlds
But It's not 100% broken.

**Comment by McJty** [comment]
Never seen this before. Very weird. Not sure what to do about this though

**Comment by ljt1477059273** [comment]
I think it may also have something to do with OptiFine ,If the front block contains Xnet items There is a probability that the client will crash.

**Comment by McJty** [comment]
So it doesn't crash without optifine?

**Comment by ljt1477059273** [comment]
Both yes and no have the same probability of collapse.
