### ISSUE TITLE
[1.16.5-5.0.20] RFTools Power/Utility Errors Due To Missing Functions

### ISSUE THREAD

**Issue by FoxMcloud5655** [McJty/McJtyLib#134]
The functions are either missing or changed in the latest build, causing these two mods to crash with the following errors:
```
[07Jul2021 15:27:03.268] [Worker-Main-2/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event FMLClientSetupEvent dispatch for modid rftoolspower
java.lang.NoSuchMethodError: mcjty.lib.client.CustomRenderTypes.func_228546_L_()V
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_51]
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962) ~[?:1.8.0_51]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:987) ~[?:1.8.0_51]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1390) ~[?:1.8.0_51]
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1746) ~[?:1.8.0_51]
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_51]
	at mcjty.lib.client.CustomRenderTypes.<clinit>(CustomRenderTypes.java:87) ~[?:1.16-5.0.20]
	at mcjty.lib.client.RenderSettings$Builder.<init>(RenderSettings.java:64) ~[?:1.16-5.0.20]
	at mcjty.lib.client.RenderSettings.builder(RenderSettings.java:54) ~[?:1.16-5.0.20]
	at mcjty.rftoolspower.modules.endergenic.client.EndergenicRenderer.<clinit>(EndergenicRenderer.java:32) ~[?:1.16-3.0.9]
	at mcjty.rftoolspower.modules.endergenic.EndergenicModule.initClient(EndergenicModule.java:64) ~[?:1.16-3.0.9]
	at mcjty.lib.modules.Modules.lambda$initClient$1(Modules.java:22) ~[?:1.16-5.0.20]
	at mcjty.lib.modules.Modules$$Lambda$28043/608824002.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51]
	at mcjty.lib.modules.Modules.initClient(Modules.java:22) ~[?:1.16-5.0.20]
	at mcjty.rftoolspower.RFToolsPower$$Lambda$12634/2050476496.accept(Unknown Source) ~[?:?]
```
And here:
```
java.lang.NoClassDefFoundError: Could not initialize class mcjty.lib.client.CustomRenderTypes
	at mcjty.lib.client.RenderSettings$Builder.<init>(RenderSettings.java:64)
	at mcjty.lib.client.RenderSettings.builder(RenderSettings.java:54)
	at mcjty.rftoolsutility.modules.environmental.client.EnvironmentalRenderer.<clinit>(EnvironmentalRenderer.java:31)
	at mcjty.rftoolsutility.modules.environmental.EnvironmentalModule.initClient(EnvironmentalModule.java:261)
	at mcjty.lib.modules.Modules.lambda$initClient$1(Modules.java:22)
	at mcjty.lib.modules.Modules$$Lambda$28043/608824002.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at mcjty.lib.modules.Modules.initClient(Modules.java:22)
	at mcjty.rftoolsutility.RFToolsUtility$$Lambda$14222/1782670938.accept(Unknown Source)
```

**Comment by BlueAmulet** [comment]
Also getting a similar issue regarding func_228546_L_, though in this crash report it says IllegalAccessError instead for me.

<details>
<summary>Stack Trace (Click to expand)</summary>

```
net.minecraftforge.fml.ModLoadingException: RFToolsPower (rftoolspower) encountered an error during the common_setup event phase
Â§7java.lang.BootstrapMethodError: java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.RenderState.func_228546_L_()V from class mcjty.lib.client.CustomRenderTypes
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:124) ~[forge:36.1] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$34(ModLoader.java:326) ~[forge:?] {re:classloading}
	at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_292] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:229) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:326) ~[forge:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:165) ~[forge:?] {re:classloading}
	at net.minecraft.client.renderer.texture.AtlasTexture.func_229220_a_(AtlasTexture.java:96) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.model.ModelBakery.processLoading(ModelBakery.java:213) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.model.ModelLoader.<init>(ModelLoader.java:72) ~[forge:?] {re:classloading}
	at net.minecraft.client.renderer.model.ModelManager.func_212854_a_(ModelManager.java:57) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.model.ModelManager.func_212854_a_(ModelManager.java:20) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.ReloadListener.func_215270_b(SourceFile:11) ~[?:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_292] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) ~[?:1.8.0_292] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_292] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_292] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_292] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_292] {}
Caused by: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.RenderState.func_228546_L_()V from class mcjty.lib.client.CustomRenderTypes
	at mcjty.lib.client.CustomRenderTypes.<clinit>(CustomRenderTypes.java:87) ~[mcjtylib:1.16-5.0.20] {re:classloading}
	at mcjty.lib.client.RenderSettings$Builder.<init>(RenderSettings.java:64) ~[mcjtylib:1.16-5.0.20] {re:classloading}
	at mcjty.lib.client.RenderSettings.builder(RenderSettings.java:54) ~[mcjtylib:1.16-5.0.20] {re:classloading}
	at mcjty.rftoolspower.modules.endergenic.client.EndergenicRenderer.<clinit>(EndergenicRenderer.java:32) ~[rftoolspower:1.16-3.0.9] {re:classloading}
	at mcjty.rftoolspower.modules.endergenic.client.ClientSetup.onTextureStitch(ClientSetup.java:19) ~[rftoolspower:1.16-3.0.9] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:36.1] {re:classloading}
	... 17 more
Caused by: java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.RenderState.func_228546_L_()V from class mcjty.lib.client.CustomRenderTypes
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_292] {}
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_292] {}
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_292] {}
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_292] {}
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_292] {}
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_292] {}
	at mcjty.lib.client.CustomRenderTypes.<clinit>(CustomRenderTypes.java:87) ~[mcjtylib:1.16-5.0.20] {re:classloading}
	at mcjty.lib.client.RenderSettings$Builder.<init>(RenderSettings.java:64) ~[mcjtylib:1.16-5.0.20] {re:classloading}
	at mcjty.lib.client.RenderSettings.builder(RenderSettings.java:54) ~[mcjtylib:1.16-5.0.20] {re:classloading}
	at mcjty.rftoolspower.modules.endergenic.client.EndergenicRenderer.<clinit>(EndergenicRenderer.java:32) ~[rftoolspower:1.16-3.0.9] {re:classloading}
	at mcjty.rftoolspower.modules.endergenic.client.ClientSetup.onTextureStitch(ClientSetup.java:19) ~[rftoolspower:1.16-3.0.9] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:36.1] {re:classloading}
	... 17 more
```

</details>

**Comment by P3rf3ctXZer0** [comment]
https://github.com/McJtyMods/RFToolsPower/issues/70#issuecomment-876089431

**Comment by McJty** [comment]
What version of Forge?

**Comment by P3rf3ctXZer0** [comment]
1.16.5 - 36.1.32

**Comment by P3rf3ctXZer0** [comment]
Just reverting to 19 at least allows booting.

**Comment by McJty** [comment]
Can you try the new McJtyLib once CurseForge approves?

**Comment by P3rf3ctXZer0** [comment]
Yes

**Comment by McJty** [comment]
It's approved

**Comment by P3rf3ctXZer0** [comment]
k

**Comment by P3rf3ctXZer0** [comment]
It works.

**Comment by McJty** [comment]
Thanks
