### ISSUE TITLE
RFTools & RFTools Dimensions make my modpack crash

### ISSUE THREAD

**Issue by Porkemon211** [McJty/McJtyLib#138]
Hi, i'm playing on 1.12.2 while trying to launch my game it crashes and say me this

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.

I'll put the crash-report too down here

java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at crazypants.enderio.integration.tic.fluids.Metal.createFluidBlock(Metal.java:68)
	at crazypants.enderio.integration.tic.TicControl$3.apply(TicControl.java:100)
	at crazypants.enderio.integration.tic.TicControl$3.apply(TicControl.java:96)
	at com.enderio.core.common.util.NNList.apply(NNList.java:141)
	at crazypants.enderio.integration.tic.TicControl.injectBlocks(TicControl.java:96)
	at crazypants.enderio.integration.tic.EnderIOIntegrationTic.injectBlocks(EnderIOIntegrationTic.java:101)
	at crazypants.enderio.base.init.ModObjectRegistry.registerAddonBlocks(ModObjectRegistry.java:102)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_266_ModObjectRegistry_registerAddonBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at crazypants.enderio.integration.tic.fluids.Metal.createFluidBlock(Metal.java:68)
	at crazypants.enderio.integration.tic.TicControl$3.apply(TicControl.java:100)
	at crazypants.enderio.integration.tic.TicControl$3.apply(TicControl.java:96)
	at com.enderio.core.common.util.NNList.apply(NNList.java:141)
	at crazypants.enderio.integration.tic.TicControl.injectBlocks(TicControl.java:96)
	at crazypants.enderio.integration.tic.EnderIOIntegrationTic.injectBlocks(EnderIOIntegrationTic.java:101)
	at crazypants.enderio.base.init.ModObjectRegistry.registerAddonBlocks(ModObjectRegistry.java:102)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_266_ModObjectRegistry_registerAddonBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	
Please help me, i've confirmed that RFTools & Dimensions are the problem but i would like to play my modpack with those mod in it too

**Comment by McJty** [comment]
Not caused by my mods. You simply have too many mods (there is a limit of 4096 blocks/items in 1.12). Either go to 1.16.5 where that limit is gone or try to use a hack mod that gets rid of that limit
