### ISSUE TITLE
RFToolsBase has failed to load correctly

### ISSUE THREAD

**Issue by Dugan9310** [McJty/McJtyLib#156]
I am receiving this error when trying to load RFToolsBase, RFToolsControl, RFToolsPower, and RFToolsBuilder, all for Minecraft ver. 1.19.2

mcytylib-1.19.7.1.4

here is the crash log for RFToolsBase....

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2023-02-07 08:14:38
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.2.4-universal.jar%23184!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19.2-43.2.4-universal.jar%23184!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:585) ~[client-1.19.2-20220805.130853-srg.jar%23179!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:438) ~[client-1.19.2-20220805.130853-srg.jar%23179!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:579) ~[client-1.19.2-20220805.130853-srg.jar%23179!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.19.2-20220805.130853-srg.jar%23179!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.19.2-20220805.130853-srg.jar%23179!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23179!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23179!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23179!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23179!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.4.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mcjty.rftoolsbase.setup.ModSetup.<init>(ModSetup.java:20) ~[rftoolsbase-1.19.1-4.0.4.jar%23173!/:1.19.1-4.0.4] {re:classloading}
-- MOD rftoolsbase --
Details:
	Mod File: /C:/Users/Dugan/AppData/Roaming/.minecraft/mods/rftoolsbase-1.19.1-4.0.4.jar
	Failure message: RFToolsBase (rftoolsbase) has failed to load correctly
		java.lang.NoSuchMethodError: 'void mcjty.rftoolsbase.setup.ModSetup.createTab(java.lang.String, java.util.function.Supplier)'
	Mod Version: 1.19.1-4.0.4
	Mod Issue URL: http://github.com/McJtyMods/RFToolsBase/issues
	Exception message: java.lang.NoSuchMethodError: 'void mcjty.rftoolsbase.setup.ModSetup.createTab(java.lang.String, java.util.function.Supplier)'
Stacktrace:
	at mcjty.rftoolsbase.setup.ModSetup.<init>(ModSetup.java:20) ~[rftoolsbase-1.19.1-4.0.4.jar%23173!/:1.19.1-4.0.4] {re:classloading}
	at mcjty.rftoolsbase.RFToolsBase.<clinit>(RFToolsBase.java:34) ~[rftoolsbase-1.19.1-4.0.4.jar%23173!/:1.19.1-4.0.4] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.4.jar%23181!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.4.jar%23180!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- MOD rftoolscontrol --
Details:
	Mod File: /C:/Users/Dugan/AppData/Roaming/.minecraft/mods/rftoolscontrol-1.19-6.0.1.jar
	Failure message: RFToolsControl (rftoolscontrol) has failed to load correctly
		java.lang.NoSuchMethodError: 'void mcjty.rftoolscontrol.setup.ModSetup.createTab(java.lang.String, java.util.function.Supplier)'
	Mod Version: 1.19-6.0.1
	Mod Issue URL: http://github.com/McJtyMods/RFToolsControl/issues
	Exception message: java.lang.NoSuchMethodError: 'void mcjty.rftoolscontrol.setup.ModSetup.createTab(java.lang.String, java.util.function.Supplier)'
Stacktrace:
	at mcjty.rftoolscontrol.setup.ModSetup.<init>(ModSetup.java:25) ~[rftoolscontrol-1.19-6.0.1.jar%23175!/:1.19-6.0.1] {re:classloading}
	at mcjty.rftoolscontrol.RFToolsControl.<clinit>(RFToolsControl.java:23) ~[rftoolscontrol-1.19-6.0.1.jar%23175!/:1.19-6.0.1] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.4.jar%23181!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.4.jar%23180!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- MOD rftoolspower --
Details:
	Mod File: /C:/Users/Dugan/AppData/Roaming/.minecraft/mods/rftoolspower-1.19-5.0.3.jar
	Failure message: RFToolsPower (rftoolspower) has failed to load correctly
		java.lang.NoSuchMethodError: 'void mcjty.rftoolspower.setup.ModSetup.createTab(java.lang.String, java.util.function.Supplier)'
	Mod Version: 1.19-5.0.3
	Mod Issue URL: http://github.com/McJtyMods/RFToolsPower/issues
	Exception message: java.lang.NoSuchMethodError: 'void mcjty.rftoolspower.setup.ModSetup.createTab(java.lang.String, java.util.function.Supplier)'
Stacktrace:
	at mcjty.rftoolspower.setup.ModSetup.<init>(ModSetup.java:14) ~[rftoolspower-1.19-5.0.3.jar%23177!/:1.19-5.0.3] {re:classloading}
	at mcjty.rftoolspower.RFToolsPower.<clinit>(RFToolsPower.java:24) ~[rftoolspower-1.19-5.0.3.jar%23177!/:1.19-5.0.3] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.4.jar%23181!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.4.jar%23180!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- MOD rftoolsbuilder --
Details:
	Mod File: /C:/Users/Dugan/AppData/Roaming/.minecraft/mods/rftoolsbuilder-1.19.1-5.1.1.jar
	Failure message: RFToolsBuilder (rftoolsbuilder) has failed to load correctly
		java.lang.NoSuchMethodError: 'void mcjty.rftoolsbuilder.setup.ModSetup.createTab(java.lang.String, java.util.function.Supplier)'
	Mod Version: 1.19.1-5.1.1
	Mod Issue URL: http://github.com/McJtyMods/RFToolsBuilder/issues
	Exception message: java.lang.NoSuchMethodError: 'void mcjty.rftoolsbuilder.setup.ModSetup.createTab(java.lang.String, java.util.function.Supplier)'
Stacktrace:
	at mcjty.rftoolsbuilder.setup.ModSetup.<init>(ModSetup.java:14) ~[rftoolsbuilder-1.19.1-5.1.1.jar%23174!/:1.19.1-5.1.1] {re:classloading}
	at mcjty.rftoolsbuilder.RFToolsBuilder.<clinit>(RFToolsBuilder.java:24) ~[rftoolsbuilder-1.19.1-5.1.1.jar%23174!/:1.19.1-5.1.1] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.4.jar%23181!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.4.jar%23180!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 561080832 bytes (535 MiB) / 905969664 bytes (864 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Mirage Driver
	Graphics card #0 vendor: DemoForge
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=2.0.105.0
	Graphics card #1 name: NVIDIA GeForce GTX 970
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x13c2
	Graphics card #1 versionInfo: DriverVersion=30.0.15.1123
	Graphics card #2 name: Intel(R) HD Graphics 4600
	Graphics card #2 vendor: Intel Corporation (0x8086)
	Graphics card #2 VRAM (MB): 1024.00
	Graphics card #2 deviceId: 0x0412
	Graphics card #2 versionInfo: DriverVersion=20.19.15.4835
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 32633.05
	Virtual memory used (MB): 8012.56
	Swap memory total (MB): 16384.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.2.4.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.4.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.2.4.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.2.4.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.4.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		BotanyPots-Forge-1.19.2-9.0.26.jar                |BotanyPots                    |botanypots                    |9.0.26              |COMMON_SET|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.19.2-16.2.17.jar                |Bookshelf                     |bookshelf                     |16.2.17             |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		BotanyTrees-Forge-1.19.2-5.0.4.jar                |BotanyTrees                   |botanytrees                   |5.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		mcjtylib-1.19-7.1.4.jar                           |McJtyLib                      |mcjtylib                      |1.19-7.1.4          |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.5.2.1007.jar                  |Just Enough Items             |jei                           |11.5.2.1007         |COMMON_SET|Manifest: NOSIGNATURE
		appliedenergistics2-forge-12.9.2.jar              |Applied Energistics 2         |ae2                           |12.9.2              |COMMON_SET|Manifest: NOSIGNATURE
		Mekanism-1.19.2-10.3.7.476.jar                    |Mekanism                      |mekanism                      |10.3.7              |COMMON_SET|Manifest: NOSIGNATURE
		MekanismTools-1.19.2-10.3.7.476.jar               |Mekanism: Tools               |mekanismtools                 |10.3.7              |COMMON_SET|Manifest: NOSIGNATURE
		MekanismAdditions-1.19.2-10.3.7.476.jar           |Mekanism: Additions           |mekanismadditions             |10.3.7              |COMMON_SET|Manifest: NOSIGNATURE
		MekanismGenerators-1.19.2-10.3.7.476.jar          |Mekanism: Generators          |mekanismgenerators            |10.3.7              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.2-43.2.4-universal.jar                 |Forge                         |forge                         |43.2.4              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		flywheel-forge-1.19.2-0.6.8.a-14.jar              |Flywheel                      |flywheel                      |0.6.8.a-14          |COMMON_SET|Manifest: NOSIGNATURE
		rftoolsbase-1.19.1-4.0.4.jar                      |RFToolsBase                   |rftoolsbase                   |1.19.1-4.0.4        |ERROR     |Manifest: NOSIGNATURE
		rftoolscontrol-1.19-6.0.1.jar                     |RFToolsControl                |rftoolscontrol                |1.19-6.0.1          |ERROR     |Manifest: NOSIGNATURE
		rftoolsdim-1.19-9.1.0.jar                         |RFToolsDimensions             |rftoolsdim                    |1.19-9.1.0          |COMMON_SET|Manifest: NOSIGNATURE
		rftoolspower-1.19-5.0.3.jar                       |RFToolsPower                  |rftoolspower                  |1.19-5.0.3          |ERROR     |Manifest: NOSIGNATURE
		rftoolsbuilder-1.19.1-5.1.1.jar                   |RFToolsBuilder                |rftoolsbuilder                |1.19.1-5.1.1        |ERROR     |Manifest: NOSIGNATURE
		create-1.19.2-0.5.0.i.jar                         |Create                        |create                        |0.5.0.i             |COMMON_SET|Manifest: NOSIGNATURE
		StorageDrawers-1.19-11.1.2.jar                    |Storage Drawers               |storagedrawers                |11.1.2              |COMMON_SET|Manifest: NOSIGNATURE
	Flywheel Backend: GL33 Instanced Arrays
	Crash Report UUID: 7194dccc-4181-4411-9c86-fa6c36c43279
	FML: 43.2
	Forge: net.minecraftforge:43.2.4

**Comment by Nuttacon** [comment]
There seems to be an issue with a recent change to function parameters in **mcjty.lib.setup**:

`protected void createTab(String name, Supplier<ItemStack> stack)`

changed to:

`protected void createTab(String modid, String name, Supplier<ItemStack> stack)`

```
[22:09:32] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: rftoolsbase, class mcjty.rftoolsbase.RFToolsBase
java.lang.NoSuchMethodError: 'void mcjty.rftoolsbase.setup.ModSetup.createTab(java.lang.String, java.util.function.Supplier)'
	at mcjty.rftoolsbase.setup.ModSetup.<init>(ModSetup.java:20) ~[rftoolsbase-1.19.1-4.0.4.jar%23176!/:1.19.1-4.0.4] {re:classloading}
	at mcjty.rftoolsbase.RFToolsBase.<clinit>(RFToolsBase.java:34) ~[rftoolsbase-1.19.1-4.0.4.jar%23176!/:1.19.1-4.0.4] {re:classloading}

[22:09:32] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: rftoolsdim, class mcjty.rftoolsdim.RFToolsDim
java.lang.NoSuchMethodError: 'void mcjty.rftoolsdim.setup.ModSetup.createTab(java.lang.String, java.util.function.Supplier)'
	at mcjty.rftoolsdim.setup.ModSetup.<init>(ModSetup.java:29) ~[rftoolsdim-1.18-8.0.10.jar%23177!/:1.18-8.0.10] {re:classloading}
	at mcjty.rftoolsdim.RFToolsDim.<clinit>(RFToolsDim.java:40) ~[rftoolsdim-1.18-8.0.10.jar%23177!/:1.18-8.0.10] {re:classloading}
```
and presumably at similar places in the other mods calling this function.

This was using the latest Minecraft 1.19.2 JARs: mcjtylib-1.19-7.2.1, rftoolsbase-1.19.1-4.0.4, and rftoolsdim-1.18-8.0.10.

**Comment by McJty** [comment]
You need RFToolsBase 4.1.6 and certainly not the 1.18 version of RFTools Dimensions
