### ISSUE TITLE
Having an issue in 1.20.1

### ISSUE THREAD

**Issue by MrJakezz** [McJty/McJtyLib#168]
@McJty 
I'm currently using McJtyLib (1.20-8.0.5), RFTools Base (1.20-5.0.4) and RFTools Dimensions (1.20-11.0.7) in my modpack but it keeps crashing consistantly. I tried everything like downgrading the lib and its related mods but i cant fix it. Here's the last crash report:

```
`---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-07-07 21:38:47
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "mcjty.rftoolsdim.modules.dimlets.data.DimletType.ordinal()" because the return value of "mcjty.rftoolsdim.modules.dimlets.data.DimletKey.type()" is null
	at mcjty.rftoolsdim.modules.dimlets.data.DimletTools.isValidDimlet(DimletTools.java:283) ~[rftoolsdim-1.20-11.0.7.jar%23308!/:1.20-11.0.7] {re:classloading}
	at mcjty.rftoolsdim.modules.dimlets.data.DimletDictionary.register(DimletDictionary.java:35) ~[rftoolsdim-1.20-11.0.7.jar%23308!/:1.20-11.0.7] {re:classloading}
	at mcjty.rftoolsdim.modules.dimlets.data.DimletDictionary.lambda$readPackage$0(DimletDictionary.java:182) ~[rftoolsdim-1.20-11.0.7.jar%23308!/:1.20-11.0.7] {re:classloading}
	at mcjty.rftoolsdim.modules.dimlets.data.DimletPackages.readPackage(DimletPackages.java:164) ~[rftoolsdim-1.20-11.0.7.jar%23308!/:1.20-11.0.7] {re:classloading}
	at mcjty.rftoolsdim.modules.dimlets.data.DimletDictionary.readPackage(DimletDictionary.java:182) ~[rftoolsdim-1.20-11.0.7.jar%23308!/:1.20-11.0.7] {re:classloading}
	at mcjty.rftoolsdim.setup.ForgeEventHandlers.onServerStarted(ForgeEventHandlers.java:107) ~[rftoolsdim-1.20-11.0.7.jar%23308!/:1.20-11.0.7] {re:classloading}
	at mcjty.rftoolsdim.setup.__ForgeEventHandlers_onServerStarted_ServerStartedEvent.invoke(.dynamic) ~[rftoolsdim-1.20-11.0.7.jar%23308!/:1.20-11.0.7] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:115) ~[forge-1.20.1-47.2.0-universal.jar%23335!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:638) ~[client-1.20.1-20230612.114412-srg.jar%23330!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23330!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1750400680 bytes (1669 MiB) / 4529848320 bytes (4320 MiB) up to 16777216000 bytes (16000 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i7-13700H
	Identifier: Intel64 Family 6 Model 186 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.92
	Number of physical packages: 1
	Number of physical CPUs: 14
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 4060 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x28a0
	Graphics card #0 versionInfo: DriverVersion=32.0.15.5585
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37363.73
	Virtual memory used (MB): 16441.57
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 7.02
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:inventorysorter (incompatible), mod:puffish_skills, mod:supermartijn642configlib (incompatible), mod:editenchanting, mod:cucumber, mod:quarryplus, mod:openpartiesandclaims (incompatible), mod:geckolib, mod:playeranimator (incompatible), mod:jei, mod:tesseract, mod:hammerlib, mod:projecte, mod:mcwwindows, mod:caelus (incompatible), mod:waystones, mod:xaeroworldmap (incompatible), mod:travelersbackpack, mod:naturescompass, mod:mixinextras (incompatible), mod:toolleveling (incompatible), mod:mcjtylib, mod:rftoolsbase, mod:mcwdoors, mod:balm, mod:inventorypets (incompatible), mod:carryon (incompatible), mod:jeresources, mod:extradisks, mod:forge, mod:shetiphiancore, mod:tlskincape (incompatible), mod:supplementaries, mod:mob_grinding_utils (incompatible), mod:refinedstorage, mod:mcwpaths, mod:ironchest, mod:cofh_core, mod:thermal, mod:mcwbridges, mod:industrialforegoing (incompatible), mod:theoneprobe, mod:moonlight (incompatible), mod:endertanks, mod:thermal_innovation, mod:titanium (incompatible), mod:immersiveengineering (incompatible), mod:mixinsquared (incompatible), mod:ironfurnaces, mod:mcwtrpdoors, mod:mcwfences, mod:supermartijn642corelib, mod:chickenchunks (incompatible), mod:enderio, mod:mysticaladaptations, mod:mysticalagriculture, mod:mysticalagradditions, mod:easy_villagers, mod:solarflux (incompatible), mod:curios (incompatible), mod:mekanism, mod:reliquary (incompatible), mod:patchouli (incompatible), mod:xaerominimap (incompatible), mod:itemcollectors (incompatible), mod:thermal_cultivation, mod:storagedrawers (incompatible), mod:fluxnetworks (incompatible), mod:irons_spellbooks, mod:thermal_foundation, mod:thermal_expansion, mod:elevatorid, mod:rftoolsdim, mod:constructionwand, mod:mcwroofs, mod:architectury (incompatible), mod:itemfilters (incompatible), mod:appleskin (incompatible), mod:mcwfurnitures, mod:cupboard (incompatible), mod:pufferfish_unofficial_additions (incompatible), mod:chunkloaders, mod:majruszsenchantments (incompatible), mod:fallingtree (incompatible), mod:codechickenlib (incompatible), mod:enderstorage (incompatible), mod:thermal_dynamics, mod:majruszlibrary (incompatible), mod:mcwlights, SolarFlux, Supplementaries Generated Pack
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: Solo
	OptiFine Version: OptiFine_1.20.1_HD_U_I6_pre6
	OptiFine Build: 20230727-130058
	Render Distance Chunks: 20
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 555.85
	OpenGlRenderer: NVIDIA GeForce RTX 4060 Laptop GPU/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 20
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		kotori_scala@3.3.1-build-0
		javafml@null
	Mod List: 
		inventorysorter-1.20.1-23.0.1.jar                 |Simple Inventory Sorter       |inventorysorter               |23.0.1              |DONE      |Manifest: NOSIGNATURE
		puffish_skills-0.11.5-1.20-forge.jar              |Pufferfish's Skills           |puffish_skills                |0.11.5              |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.8-forge-mc1.20.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.8               |DONE      |Manifest: NOSIGNATURE
		DisenchantmentEditTable-1.20-1.1.2.jar            |Disenchantment Edit Table     |editenchanting                |1.1.2               |DONE      |Manifest: NOSIGNATURE
		Cucumber-1.20.1-7.0.8.jar                         |Cucumber Library              |cucumber                      |7.0.8               |DONE      |Manifest: NOSIGNATURE
		AdditionalEnchantedMiner-1.20.1-1201.0.58.jar     |QuarryPlus                    |quarryplus                    |1201.0.58           |DONE      |Manifest: ef:50:af:b3:03:e0:3e:70:a7:ef:78:77:a5:4d:d4:b5:07:ec:df:9d:d6:f3:12:13:c9:3c:cd:9a:0a:3e:6b:43
		open-parties-and-claims-forge-1.20.1-0.22.2.jar   |Open Parties and Claims       |openpartiesandclaims          |0.22.2              |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.20.1-4.4.4.jar                   |GeckoLib 4                    |geckolib                      |4.4.4               |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2-rc1+1.20.jar     |Player Animator               |playeranimator                |1.0.2-rc1+1.20      |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.3.0.4.jar                     |Just Enough Items             |jei                           |15.3.0.4            |DONE      |Manifest: NOSIGNATURE
		tesseract-1.0.35a-forge-mc1.20.1.jar              |Tesseract                     |tesseract                     |1.0.35a             |DONE      |Manifest: NOSIGNATURE
		HammerLib-1.20.1-20.1.29.jar                      |HammerLib                     |hammerlib                     |20.1.29             |DONE      |Manifest: 97:e8:52:e9:b3:f0:1b:83:57:4e:83:15:f7:e7:76:51:c6:60:5f:2b:45:59:19:a7:31:9e:98:69:56:4f:01:3c
		ProjectE-1.20.1-PE1.0.1.jar                       |ProjectE                      |projecte                      |1.0.1               |DONE      |Manifest: NOSIGNATURE
		mcw-windows-2.2.1-mc1.20.1forge.jar               |Macaw's Windows               |mcwwindows                    |2.2.1               |DONE      |Manifest: NOSIGNATURE
		caelus-forge-3.2.0+1.20.1.jar                     |Caelus API                    |caelus                        |3.2.0+1.20.1        |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.20-14.1.3.jar                   |Waystones                     |waystones                     |14.1.3              |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.38.4_Forge_1.20.jar              |Xaero's World Map             |xaeroworldmap                 |1.38.4              |DONE      |Manifest: NOSIGNATURE
		travelersbackpack-forge-1.20.1-9.1.14.jar         |Traveler's Backpack           |travelersbackpack             |9.1.14              |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.20.1-1.11.2-forge.jar            |Nature's Compass              |naturescompass                |1.20.1-1.11.2-forge |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.3.5.jar                       |MixinExtras                   |mixinextras                   |0.3.5               |DONE      |Manifest: NOSIGNATURE
		toolleveling-forge-1.20.1-2.0.0.jar               |ToolLeveling+                 |toolleveling                  |1.20.1-2.0.0        |DONE      |Manifest: NOSIGNATURE
		mcjtylib-1.20-8.0.5.jar                           |McJtyLib                      |mcjtylib                      |1.20-8.0.5          |DONE      |Manifest: NOSIGNATURE
		rftoolsbase-1.20-5.0.4.jar                        |RFToolsBase                   |rftoolsbase                   |1.20-5.0.4          |DONE      |Manifest: NOSIGNATURE
		mcw-doors-1.1.0forge-mc1.20.1.jar                 |Macaw's Doors                 |mcwdoors                      |1.1.0               |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.2.2.jar                       |Balm                          |balm                          |7.2.2               |DONE      |Manifest: NOSIGNATURE
		inventorypets-1.20.1-2.1.1.jar                    |Inventory Pets                |inventorypets                 |2.1.1               |DONE      |Manifest: NOSIGNATURE
		carryon-forge-1.20.1-2.1.2.7.jar                  |Carry On                      |carryon                       |2.1.2.7             |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.20.1-1.4.0.247.jar          |Just Enough Resources         |jeresources                   |1.4.0.247           |DONE      |Manifest: NOSIGNATURE
		ExtraDisks-1.20.1-3.0.2.jar                       |Extra Disks                   |extradisks                    |1.20.1-3.0.2        |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.0-universal.jar                 |Forge                         |forge                         |47.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		shetiphiancore-forge-1.20.1-1.3.jar               |ShetiPhian-Core               |shetiphiancore                |1.20.1-1.3          |DONE      |Manifest: NOSIGNATURE
		tl_skin_cape_forge_1.20_1.20.1-1.32.jar           |TLSkinCape                    |tlskincape                    |1.32                |DONE      |Manifest: ef:fe:e7:59:91:bb:3a:06:c1:94:f4:f3:9c:3e:26:69:47:fa:2e:c5:53:d3:38:21:65:cc:04:75:e7:61:19:40
		supplementaries-1.20-2.8.11.jar                   |Supplementaries               |supplementaries               |1.20-2.8.11         |DONE      |Manifest: NOSIGNATURE
		mob_grinding_utils-1.20.1-1.1.0.jar               |Mob Grinding Utils            |mob_grinding_utils            |1.20.1-1.1.0        |DONE      |Manifest: NOSIGNATURE
		refinedstorage-1.12.4.jar                         |Refined Storage               |refinedstorage                |1.12.4              |DONE      |Manifest: NOSIGNATURE
		mcw-paths-1.0.5-1.20.1forge.jar                   |Macaw's Paths and Pavings     |mcwpaths                      |1.0.5               |DONE      |Manifest: NOSIGNATURE
		ironchest-1.20.1-14.4.4.jar                       |Iron Chests                   |ironchest                     |1.20.1-14.4.4       |DONE      |Manifest: NOSIGNATURE
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		cofh_core-1.20.1-11.0.0.51.jar                    |CoFH Core                     |cofh_core                     |11.0.0              |DONE      |Manifest: NOSIGNATURE
		thermal_core-1.20.1-11.0.2.18.jar                 |Thermal Series                |thermal                       |11.0.2              |DONE      |Manifest: NOSIGNATURE
		mcw-bridges-3.0.0-mc1.20.1forge.jar               |Macaw's Bridges               |mcwbridges                    |3.0.0               |DONE      |Manifest: NOSIGNATURE
		industrial-foregoing-1.20.1-3.5.16.jar            |Industrial Foregoing          |industrialforegoing           |3.5.16              |DONE      |Manifest: NOSIGNATURE
		theoneprobe-1.20.1-10.0.2.jar                     |The One Probe                 |theoneprobe                   |1.20.1-10.0.2       |DONE      |Manifest: NOSIGNATURE
		moonlight-1.20-2.11.22-forge.jar                  |Moonlight Library             |moonlight                     |1.20-2.11.22        |DONE      |Manifest: NOSIGNATURE
		endertanks-forge-1.20.1-1.3.jar                   |EnderTanks                    |endertanks                    |1.20.1-1.3          |DONE      |Manifest: NOSIGNATURE
		thermal_innovation-1.20.1-11.0.0.21.jar           |Thermal Innovation            |thermal_innovation            |11.0.0              |DONE      |Manifest: NOSIGNATURE
		titanium-1.20.1-3.8.27.jar                        |Titanium                      |titanium                      |3.8.27              |DONE      |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.20.1-10.1.0-171.jar        |Immersive Engineering         |immersiveengineering          |1.20.1-10.1.0-171   |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		mixinsquared-forge-0.1.1.jar                      |MixinSquared                  |mixinsquared                  |0.1.1               |DONE      |Manifest: NOSIGNATURE
		ironfurnaces-1.20.1-4.1.6.jar                     |Iron Furnaces                 |ironfurnaces                  |4.1.6               |DONE      |Manifest: NOSIGNATURE
		mcw-trapdoors-1.1.3-mc1.20.1forge.jar             |Macaw's Trapdoors             |mcwtrpdoors                   |1.1.3               |DONE      |Manifest: NOSIGNATURE
		mcw-fences-1.1.1-mc1.20.1forge.jar                |Macaw's Fences and Walls      |mcwfences                     |1.1.1               |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.17-forge-mc1.20.1.jar  |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.17              |DONE      |Manifest: NOSIGNATURE
		ChickenChunks-1.20.1-2.10.0.100-universal.jar     |ChickenChunks                 |chickenchunks                 |2.10.0.100          |DONE      |Manifest: NOSIGNATURE
		EnderIO-1.20.1-6.0.25-alpha.jar                   |Ender IO                      |enderio                       |6.0.25-alpha        |DONE      |Manifest: NOSIGNATURE
		MysticalAdaptations-1.20.1-1.0.1.jar              |Mystical Adaptations          |mysticaladaptations           |1.20.1-1.0.1        |DONE      |Manifest: NOSIGNATURE
		MysticalAgriculture-1.20.1-7.0.11.jar             |Mystical Agriculture          |mysticalagriculture           |7.0.11              |DONE      |Manifest: NOSIGNATURE
		MysticalAgradditions-1.20.1-7.0.3.jar             |Mystical Agradditions         |mysticalagradditions          |7.0.3               |DONE      |Manifest: NOSIGNATURE
		easy-villagers-forge-1.20.1-1.1.4.jar             |Easy Villagers                |easy_villagers                |1.20.1-1.1.4        |DONE      |Manifest: NOSIGNATURE
		SolarFluxReborn-1.20.1-20.1.6.jar                 |Solar Flux Reborn             |solarflux                     |20.1.6              |DONE      |Manifest: 97:e8:52:e9:b3:f0:1b:83:57:4e:83:15:f7:e7:76:51:c6:60:5f:2b:45:59:19:a7:31:9e:98:69:56:4f:01:3c
		curios-forge-5.9.0+1.20.1.jar                     |Curios API                    |curios                        |5.9.0+1.20.1        |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.20.1-10.4.8.43.jar                     |Mekanism                      |mekanism                      |10.4.8              |DONE      |Manifest: NOSIGNATURE
		reliquary-1.20.1-2.0.41.1229.jar                  |Reliquary                     |reliquary                     |1.20.1-2.0.41.1229  |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.20.1-84-FORGE.jar                     |Patchouli                     |patchouli                     |1.20.1-84-FORGE     |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_24.1.1_Forge_1.20.jar              |Xaero's Minimap               |xaerominimap                  |24.1.1              |DONE      |Manifest: NOSIGNATURE
		itemcollectors-1.1.10-forge-mc1.20.jar            |Item Collectors               |itemcollectors                |1.1.10              |DONE      |Manifest: NOSIGNATURE
		thermal_cultivation-1.20.1-11.0.0.22.jar          |Thermal Cultivation           |thermal_cultivation           |11.0.0              |DONE      |Manifest: NOSIGNATURE
		storagedrawers-1.20.1-12.0.3.jar                  |Storage Drawers               |storagedrawers                |12.0.3              |DONE      |Manifest: NOSIGNATURE
		FluxNetworks-1.20.1-7.2.1.15.jar                  |Flux Networks                 |fluxnetworks                  |7.2.1.15            |DONE      |Manifest: NOSIGNATURE
		irons_spellbooks-1.20.1-3.1.6.jar                 |Iron's Spells 'n Spellbooks   |irons_spellbooks              |1.20.1-3.1.6        |DONE      |Manifest: NOSIGNATURE
		thermal_foundation-1.20.1-11.0.2.64.jar           |Thermal Foundation            |thermal_foundation            |11.0.2              |DONE      |Manifest: NOSIGNATURE
		thermal_expansion-1.20.1-11.0.0.27.jar            |Thermal Expansion             |thermal_expansion             |11.0.0              |DONE      |Manifest: NOSIGNATURE
		elevatorid-1.20.1-lex-1.9.jar                     |Elevator Mod                  |elevatorid                    |1.20.1-lex-1.9      |DONE      |Manifest: NOSIGNATURE
		rftoolsdim-1.20-11.0.7.jar                        |RFToolsDimensions             |rftoolsdim                    |1.20-11.0.7         |DONE      |Manifest: NOSIGNATURE
		constructionwand-1.20.1-2.11.jar                  |Construction Wand             |constructionwand              |1.20.1-2.11         |DONE      |Manifest: NOSIGNATURE
		mcw-roofs-2.3.0-mc1.20.1forge.jar                 |Macaw's Roofs                 |mcwroofs                      |2.3.0               |DONE      |Manifest: NOSIGNATURE
		architectury-9.2.14-forge.jar                     |Architectury                  |architectury                  |9.2.14              |DONE      |Manifest: NOSIGNATURE
		item-filters-forge-2001.1.0-build.59.jar          |Item Filters                  |itemfilters                   |2001.1.0-build.59   |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.20.1-2.5.1.jar                |AppleSkin                     |appleskin                     |2.5.1+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		mcw-furniture-3.2.2-mc1.20.1forge.jar             |Macaw's Furniture             |mcwfurnitures                 |3.2.2               |DONE      |Manifest: NOSIGNATURE
		cupboard-1.20.1-2.6.jar                           |Cupboard utilities            |cupboard                      |1.20.1-2.6          |DONE      |Manifest: NOSIGNATURE
		pufferfish_unofficial_additions-1.20.1-2.0.2-all.j|Pufferfish's Unofficial Additi|pufferfish_unofficial_addition|2.0.2               |DONE      |Manifest: NOSIGNATURE
		chunkloaders-1.2.8a-forge-mc1.20.1.jar            |Chunk Loaders                 |chunkloaders                  |1.2.8a              |DONE      |Manifest: NOSIGNATURE
		majruszs-enchantments-forge-1.20.1-1.10.8.jar     |Majrusz's Enchantments        |majruszsenchantments          |1.10.8              |DONE      |Manifest: NOSIGNATURE
		FallingTree-1.20.1-4.3.4.jar                      |FallingTree                   |fallingtree                   |4.3.4               |DONE      |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		CodeChickenLib-1.20.1-4.4.0.509-universal.jar     |CodeChicken Lib               |codechickenlib                |4.4.0.509           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		EnderStorage-1.20.1-2.11.0.188-universal.jar      |EnderStorage                  |enderstorage                  |2.11.0.188          |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		thermal_dynamics-1.20.1-11.0.0.21.jar             |Thermal Dynamics              |thermal_dynamics              |11.0.0              |DONE      |Manifest: NOSIGNATURE
		majrusz-library-forge-1.20.1-7.0.8.jar            |Majrusz Library               |majruszlibrary                |7.0.8               |DONE      |Manifest: NOSIGNATURE
		mcw-lights-1.0.6-mc1.20.1forge.jar                |Macaw's Lights and Lamps      |mcwlights                     |1.0.6               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: cf881370-12c5-4126-9a94-f19493196548
	FML: 47.2
	Forge: net.minecraftforge:47.2.0`
```
	
Crash txt file is attached if need.
[crash-2024-07-07_21.38.46-server.txt](https://github.com/user-attachments/files/16120345/crash-2024-07-07_21.38.46-server.txt)

**Comment by McJty** [comment]
Do you have custom dimlets or any special configuration?

**Comment by MrJakezz** [comment]
> Do you have custom dimlets or any special configuration?

No I don't have any custom dimlets and I didn't touch any config file.

**Comment by McJty** [comment]
Ok two things:
- Get rid of optifine. Optifine is a bad mod that messes with things. It could very well be the cause here. If you need shaders then there is rubidium/occulus instead. Those work much better
-  You probably want to add rftoolsutility. Otherwise you can't get in the generated dimensions

**Comment by MrJakezz** [comment]
> Ok two things:
> 
> * Get rid of optifine. Optifine is a bad mod that messes with things. It could very well be the cause here. If you need shaders then there is rubidium/occulus instead. Those work much better
> * You probably want to add rftoolsutility. Otherwise you can't get in the generated dimensions

Alright gonna try that when I'm free. Thanks for your time I'll reply & close this thread if everything goes fine.

**Comment by MrJakezz** [comment]
@McJty 
Hi again. It seems like deleting OptiFine doesn't fix the issue I'm currently having. Still getting the dimlet error.
