### ISSUE TITLE
NoClassDefFoundError when launching

### ISSUE THREAD

**Issue by dashkal16** [McJty/McJtyLib#20]
I get a NoClassDefFoundError when launching minecraft.
Note that the .class blamed from McJtyLib is present in the .jar

```
net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: mcjty/deepresonance/blocks/laser/LaserTileEntity
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:610)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:255)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.NoClassDefFoundError: mcjty/deepresonance/blocks/laser/LaserTileEntity
    at mcjty.deepresonance.blocks.laser.LaserBonusConfiguration.init(LaserBonusConfiguration.java:48)
    at mcjty.deepresonance.proxy.CommonProxy.readMainConfig(CommonProxy.java:61)
    at mcjty.deepresonance.proxy.CommonProxy.preInit(CommonProxy.java:39)
    at mcjty.deepresonance.proxy.ClientProxy.preInit(ClientProxy.java:24)
    at mcjty.deepresonance.DeepResonance.preInit(DeepResonance.java:131)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:595)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:607)
    ... 18 more
Caused by: java.lang.ClassNotFoundException: mcjty.deepresonance.blocks.laser.LaserTileEntity
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 50 more
Caused by: java.lang.NoClassDefFoundError: mcjty/lib/entity/GenericEnergyReceiverTileEntity
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 52 more
Caused by: java.lang.ClassNotFoundException: mcjty.lib.entity.GenericEnergyReceiverTileEntity
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 56 more
```

Versions:
Minecraft 1.10.2
Forge 1.10.2-12.18.1.2076
Deep Resonance 1.10-1.2.3
ElecCore 1.9.4-1.5.311
McJtyLib 1.12.2.1.0
RFTools 1.1-5.23
RFToolsCtrl 1.10-0.1.0beta6
RFTools Dimensions 1.10-4.30beta49
The One Probe 1.10-1.1.1

No other mods

**Comment by McJty** [comment]
Upgrade forge
