### ISSUE TITLE
[1.10.2] InventoryHelper.insertItemsItemHandlerWithUndo() will try to insert null stacks

### ISSUE THREAD

**Issue by HenryLoenwind** [McJty/McJtyLib#28]
https://github.com/McJty/McJtyLib/blob/1.10/src/main/java/mcjty/lib/container/InventoryHelper.java#L256-L260

This sets the stacks that could be inserted completely to null in "s". If there is a second stack to be inserted and a second slot to be inserted into, that null value will be passed to IItemHandler.insertItem().

```
Caused by: java.lang.NullPointerException
	at crazypants.enderio.capability.InventorySlot.insertItem(InventorySlot.java:109) ~[InventorySlot.class:?]
	at crazypants.enderio.capability.EnderInventory$View.insertItem(EnderInventory.java:196) ~[EnderInventory$View.class:?]
	at crazypants.enderio.machine.AbstractCapabilityMachineEntity$Side.insertItem(AbstractCapabilityMachineEntity.java:165) ~[AbstractCapabilityMachineEntity$Side.class:?]
	at mcjty.lib.container.InventoryHelper.insertItemsItemHandlerWithUndo(InventoryHelper.java:256) ~[InventoryHelper.class:?]
	at mcjty.lib.container.InventoryHelper.insertItemsAtomic(InventoryHelper.java:290) ~[InventoryHelper.class:?]
	at mcjty.rftools.blocks.builder.BuilderTileEntity.checkAndInsertItems(BuilderTileEntity.java:1390) ~[BuilderTileEntity.class:?]
	at mcjty.rftools.blocks.builder.BuilderTileEntity.quarryBlock(BuilderTileEntity.java:1141) ~[BuilderTileEntity.class:?]
	at mcjty.rftools.blocks.builder.BuilderTileEntity.handleSingleBlock(BuilderTileEntity.java:944) ~[BuilderTileEntity.class:?]
	at mcjty.rftools.blocks.builder.BuilderTileEntity.handleBlockShaped(BuilderTileEntity.java:849) ~[BuilderTileEntity.class:?]
	at mcjty.rftools.blocks.builder.BuilderTileEntity.checkStateServerShaped(BuilderTileEntity.java:609) ~[BuilderTileEntity.class:?]
	at mcjty.rftools.blocks.builder.BuilderTileEntity.checkStateServer(BuilderTileEntity.java:641) ~[BuilderTileEntity.class:?]
	at mcjty.rftools.blocks.builder.BuilderTileEntity.func_73660_a(BuilderTileEntity.java:623) ~[BuilderTileEntity.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1804) ~[aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620) ~[ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
```

**Comment by McJty** [comment]
That code is from the 1.10 branch which is not used. The 1.11 branch is used for the 1.10/1.11 version of my mod
