### ISSUE TITLE
Game Crash caused by rftools and rtfoolscontrol

### ISSUE THREAD

**Issue by 5trgV** [McJty/McJtyLib#40]
Hi me again.
I fixed the problem with McJtyLib_ng but as the game was almost loaded it crashed again.
With the following console output:
`// Oops.

Time: 9/23/17 4:34 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from RFTools (rftools)
Caused by: java.lang.NoSuchMethodError: mcjty.lib.network.PacketRequestServerListHandler.<init>(Lmcjty/typed/Type;)V
	at mcjty.rftools.network.PacketGetHudLog$Handler.<init>(PacketGetHudLog.java:28)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at java.lang.Class.newInstance(Class.java:438)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.instantiate(SimpleNetworkWrapper.java:171)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.registerMessage(SimpleNetworkWrapper.java:164)
	at mcjty.rftools.network.RFToolsMessages.registerNetworkMessages(RFToolsMessages.java:73)
	at mcjty.rftools.proxy.CommonProxy.preInit(CommonProxy.java:109)
	at mcjty.rftools.proxy.ClientProxy.preInit(ClientProxy.java:46)
	at mcjty.rftools.RFTools.preInit(RFTools.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:624)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:259)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 735225208 bytes (701 MB) / 1930375168 bytes (1840 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2488 77 mods loaded, 77 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2488.jar) 
	UCH	Forge{12.18.3.2488} [Minecraft Forge] (forge-1.10.2-12.18.3.2488.jar) 
	UCH	appliedenergistics2-core{rv4-stable-1} [Applied Energistics 2 Core] (minecraft.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCH	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCH	appliedenergistics2{rv4-stable-1} [Applied Energistics 2] (appliedenergistics2-rv4-stable-1.jar) 
	UCH	bdlib{1.12.4.24} [BD Lib] (bdlib-1.12.4.24-mc1.10.2.jar) 
	UCH	ae2stuff{0.6.0.9} [AE2 Stuff] (ae2stuff-0.6.0.9-mc1.10.2.jar) 
	UCH	infinitylib{1.10.2-0.11.0} [InfinityLib] (infinitylib-0.11.0.jar) 
	UCH	agricraft{2.0.0-0.10.0-a19} [AgriCraft] (agricraft-2.0.0-0.10.0-a19.jar) 
	UCH	architecturecraft{1.7.3} [ArchitectureCraft] (ArchitectureCraft-1.7.3-mc1.10.2.jar) 
	UCH	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCH	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2 (1).jar) 
	UCH	CodeChickenLib{2.5.9.283} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCH	avaritia{${mod_version}} [Avaritia] (Avaritia-1.10.2-2.1.0.1-universal.jar) 
	UCH	Baubles{1.3.11} [Baubles] (Baubles-1.10.2-1.3.11.jar) 
	UCH	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar) 
	UCH	BiblioCraft{2.2.5} [BiblioCraft] (BiblioCraft[v2.2.5][MC1.10.2].jar) 
	UCH	bookshelf{1.4.4.347} [Bookshelf] (Bookshelf-1.10.2-1.4.4.347.jar) 
	UCH	cofhcore{4.1.12} [CoFH Core] (CoFHCore-1.10.2-4.1.12.17-universal.jar) 
	UCH	brandonscore{2.1.12} [Brandon's Core] (BrandonsCore-1.10.2-2.1.12.130-universal.jar) 
	UCH	Chameleon{1.10.2-2.3.0} [Chameleon] (Chameleon-1.10.2-2.3.0.jar) 
	UCH	ChestTransporter{2.5.18} [Chest Transporter] (ChestTransporter-1.10.2-2.5.18.jar) 
	UCH	chisel{MC1.10.2-0.0.14.33} [Chisel] (Chisel-MC1.10.2-0.0.14.33.jar) 
	UCH	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCH	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
	UCH	chiselsandbits{12.15} [Chisels & Bits] (chiselsandbits-12.15.jar) 
	UCH	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UCH	darkutils{1.1.8.finalrc2} [Dark Utilities] (DarkUtilities-1.1.8.finalrc2.jar) 
	UCH	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.2_1.10.2.jar) 
	UCH	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.10.2.jar) 
	UCH	draconicevolution{2.1.6} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.1.6.263-universal.jar) 
	UCH	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	UCH	EnderIO{1.10.2-3.1.193} [Ender IO] (EnderIO-1.10.2-3.1.193.jar) 
	UCH	EnderStorage{2.2.1.106} [EnderStorage] (EnderStorage-1.10.2-2.2.1.106-universal.jar) 
	UCH	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.6.3.jar) 
	UCH	sonarcore{3.3.0} [SonarCore] (SonarCore-1.10.2-3.3.0.jar) 
	UCH	fluxnetworks{1.2.8} [FluxNetworks] (FluxNetworks-1.10.2-1.2.8.jar) 
	UCH	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.5.3.jar) 
	UCH	funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.10.2-alpha-0.0.3.jar) 
	UCH	gravestone{1.5.13} [Gravestone Mod] (gravestone-1.5.13.jar) 
	UCH	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.3-46.jar) 
	UCH	hammercore{1.9.4.3} [Hammer Core] (HammerCore-1.10.2-1.9.4.3.jar) 
	UCH	immersiveengineering{0.10-61} [Immersive Engineering] (ImmersiveEngineering-0.10-61.jar) 
	UCH	inventorytweaks{1.62-dev-66-c082db3} [Inventory Tweaks] (InventoryTweaks-1.62-dev-66.jar) 
	UCH	ironchest{1.10.2-7.0.15.804} [Iron Chest] (ironchest-1.10.2-7.0.15.804.jar) 
	UCH	jeresources{0.5.9.3} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.9.3.jar) 
	UCH	LunatriusCore{1.1.2.38} [LunatriusCore] (LunatriusCore-1.10.2-1.1.2.38-universal.jar) 
	UCH	malisiscore{1.10.2-4.4.0} [MalisisCore] (malisiscore-1.10.2-4.4.0.jar) 
	UCH	malisisdoors{1.10.2-5.2.0} [MalisisDoors] (malisisdoors-1.10.2-5.2.0.jar) 
	UCH	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCH	MrTJPCoreMod{2.0.1.20} [MrTJPCore] (MrTJPCore-1.10.2-2.0.1.20-universal.jar) 
	UCH	ProjectE{1.10.2-PE1.3.1} [ProjectE] (ProjectE-1.10.2-PE1.3.1.jar) 
	UCH	p455w0rdslib{1.0.13} [p455w0rd's Library] (p455w0rdslib-1.10.2-1.0.13.jar) 
	UCH	reborncore{2.13.6.142} [RebornCore] (RebornCore-1.10.2-2.13.6.142-universal.jar) 
	UCH	quantumstorage{3.3.6} [QuantumStorage] (QuantumStorage-1.10.2-3.3.6.jar) 
	UCH	railcraft{10.2.0} [Railcraft] (Railcraft_1.10.2-10.2.0.jar) 
	UCH	reborncore-mcmultipart{2.13.6.142} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.13.6.142-universal.jar) 
	UCE	rftools{6.13} [RFTools] (rftools-1.1x-6.13.jar) 
	UCE	rftoolscontrol{1.5.2} [RFTools Control] (rftoolsctrl-1.10-1.5.2.jar) 
	UCH	shadowmc{3.6.1} [ShadowMC] (ShadowMC-1.10.2-3.6.1.jar) 
	UCH	simplevoidworld{1.1.0.4} [SimpleVoidWorld] (Simple-Void-World-1.10.2-1.1.0.4-universal.jar) 
	UCH	simplyjetpacks{2.1.3.55} [Simply Jetpacks 2] (SimplyJetpacks2-1.10.2-2.1.3.55.jar) 
	UCH	solarfluxreborn{2.17r} [Solar Flux Reborn] (SolarFluxReborn_1.10.2-2.17r.jar) 
	UCH	stevescarts{2.1.4.83} [Steve's Carts 2] (StevesCarts-1.10.2-2.1.4.83.jar) 
	UCH	thermalfoundation{2.1.5} [Thermal Foundation] (ThermalFoundation-1.10.2-2.1.5.12-universal.jar) 
	UCH	thermalexpansion{5.1.10} [Thermal Expansion] (ThermalExpansion-1.10.2-5.1.10.25-universal.jar) 
	UCH	thermaldynamics{2.0.11} [Thermal Dynamics] (ThermalDynamics-1.10.2-2.0.11.17-universal.jar) 
	UCH	torchmaster{1.4.0.32} [TorchMaster] (torchmaster_1.10.2-1.4.0.32.jar) 
	UCH	valkyrielib{1.10.2-0.10.6} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.6.jar) 
	UCH	wanionlib{1.10.2-1.3} [WanionLib] (WanionLib-1.10.2-1.3.jar) 
	UCH	wct{0.1.32} [Wireless Crafting Terminal 2] (WirelessCraftingTerminal-1.10.2-0.1.32.jar) 
	UCH	Woot{1.10.2-1.4.1} [Woot] (woot-1.10.2-1.4.1.jar) 
	UCH	zerocore{1.10.2-0.1.1.0} [Zero CORE] (zerocore-1.10.2-0.1.1.0.jar) 
	UCH	unidict{1.10.2-2.9b} [UniDict] (UniDict-1.10.2-2.9b.jar)`

As I'm not very experienced I can only see that the mods rftools and rftoolscontrol errored in the Pre-Intit. Why is that? And how to fix it?

**Comment by McJty** [comment]
What are all the versions of mc, compatlayer, mcjtylib, rftools ?

**Comment by iyloMC** [comment]
I am having the exact same problem.

The versions installed are:
- MC 1.10.2
- CompatLayer 1.10-0.2.9
- McJtyLib 1.1x-2.4.3
- McJtyLib 1.10-2.2.0
- RFTools 1.1x-7.12

For some reason, RFTools fails to launch if I don't have BOTH of those versions of McJtyLib installed. If I take out 1.10-2.2.0, it says I'm missing "mcjtylib". If I take out 1.1x-2.4.3, it says I'm missing "mcjtylib_ng".

I also have RFToolsCtrl-1.10-1.5.2 and RFToolsDim-1.10-4.45, if that helps.

**Comment by McJty** [comment]
Don't install both versions of McJtyLib. Install only 1.1x-2.4.3. And update RFTools Control and RFTools Dimensions to the 1.1x versions as well
