### ISSUE TITLE
I have that in a crash report on loading minecraft:

### ISSUE THREAD

**Issue by arthuro555** [McJty/McJtyLib#52]
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from RFTools (rftools)
Caused by: java.lang.NoSuchMethodError: mcjty.rftools.integration.computers.OpenComputersIntegration.init()V
	at mcjty.rftools.RFTools.init(RFTools.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:805)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:334)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_65, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 241887760 bytes (230 MB) / 853917696 bytes (814 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: Minecraft 1.10.2 MCP 9.32 Powered by Forge 12.18.3.2488 41 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2488.jar) 
	UCHI	Forge{12.18.3.2488} [Minecraft Forge] (forge-1.10.2-12.18.3.2488.jar) 
	UCHI	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCHI	OpenComputers|Core{1.6.2.7} [OpenComputers (Core)] (minecraft.jar) 
	UCHI	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHI	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCHI	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHI	Aroma1997CoreHelper{1.1.1.2} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCHI	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.9.4-1.2.0.7.jar) 
	UCHI	arsmagica2{1.5.018} [Ars Magica 2] (ArsMagica2-1.10.2-1.5.0-18.jar) 
	UCHI	AnimationAPI{1.2.4} [AnimationAPI] (ArsMagica2-1.10.2-1.5.0-18.jar) 
	UCHI	Morphtool{1.0-12} [Morph-o-Tool] (Morph-o-Tool-1.0-12.jar) 
	UCHI	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHI	CodeChickenLib{2.5.9.283} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCHI	cofhcore{4.1.11} [CoFH Core] (CoFHCore-1.10.2-4.1.11.16-universal.jar) 
	UCHI	brandonscore{2.1.14} [Brandon's Core] (BrandonsCore-1.10.2-2.1.14.137-universal.jar) 
	UCHI	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UCHI	customspawner{3.10.1} [DrZhark's CustomSpawner] (CustomMobSpawner 3.10.1.jar) 
	UCHI	thermalfoundation{2.1.5} [Thermal Foundation] (ThermalFoundation-1.10.2-2.1.5.12-universal.jar) 
	UCHI	draconicevolution{2.1.8} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.1.8.273-universal.jar) 
	UCHI	mocreatures{10.0.6} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod-10.0.6.jar) 
	UCHI	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	UCHI	JEI{3.14.7.419} [Just Enough Items] (Just-Enough-Items-Mod-1.10.2.jar) 
	UCHI	EnderIO{1.10.2-3.1.183} [Ender IO] (EnderIO-1.10.2-3.1.183.jar) 
	UCHI	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.6.3.jar) 
	UCHI	sonarcore{3.3.0} [SonarCore] (SonarCore-1.10.2-3.3.0.jar) 
	UCHI	fluxnetworks{1.2.5} [FluxNetworks] (FluxNetworks-1.10.2-1.2.5.jar) 
	UCHI	geneticsreborn{1.04} [Genetics Reborn] (geneticsreborn-mc1.10.2-v1.05.jar) 
	UCHI	journeymap{1.10.2-5.5.2} [JourneyMap] (journeymap-1.10.2-5.5.2.jar) 
	UCHI	more{7.3} [M-Ore Mod] (M-Ore-Mod-1.10.2.jar) 
	UCHI	metamorph{1.1.4} [Metamorph] (metamorph-1.1.4-1.10.2.jar) 
	UCHI	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
	UCHI	OpenComputers{1.6.2.7} [OpenComputers] (OpenComputers-MC1.10.2-1.6.2.7.jar) 
	UCHI	quantumflux{2.0.11} [QuantumFlux] (quantumflux-1.10.2-2.0.11.jar) 
	UCHE	rftools{7.15} [RFTools] (rftools-1.1x-7.15.jar) 
	UCHI	securitycraft{v1.8.2.2} [SecurityCraft] (SecurityCraft-Mod-1.10.2.jar) 
	UCHI	simplyjetpacks{2.1.3.55} [Simply Jetpacks 2] (SimplyJetpacks2-1.10.2-2.1.3.55.jar) 
	UCHI	thermalexpansion{5.1.9} [Thermal Expansion] (ThermalExpansion-1.10.2-5.1.9.23-universal.jar) 
	UCHI	thermaldynamics{2.0.10} [Thermal Dynamics] (ThermalDynamics-1.10.2-2.0.10.16-universal.jar) 
	UCHI	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	Loaded coremods (and transformers): 
CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  

I asked for help because It crashes since i have rftools and your lib mod.

**Comment by McJty** [comment]
Upgrade RFTools to 7.16 and McJtyLib as well

**Comment by arthuro555** [comment]
The new version do the same.

**Comment by arthuro555** [comment]
maybe that can help : 
EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * The RF API that is being used (1.5.0 from (guessing) null) differes from that that is reported as being loaded (1.8.9R1.2.0B1 from mcjtylib-1.1x-2.5.1.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

**Comment by McJty** [comment]
Does EnderIO still include the RF API like they did before? That is no longer allowed. RF API is now part of the CoFH core package. Then this problem wouldn't occur

**Comment by josephcsible** [comment]
Make sure that CompatLayer, McJtyLib, RFTools, and OpenComputers are all up to date. If the crash still happens, pastebin a new crash log.
