### ISSUE TITLE
crash while using a Thermal wrench on a thermal item_ duct...

### ISSUE THREAD

**Issue by JasonKillsUs** [McJty/McJtyLib#75]
https://pastebin.com/Zi89ijq0

MC 1.12.2 / Forge 2705
thanks for looking into it

**Comment by AlienXAXS** [comment]
Just thought i would add to this also.
This also happens when attempting to use the Mekanism 'Configurator' on any Mekanism machine.

One would assume though that it's just any item that needs a wrench or handles a right click event from Forge.

`java.lang.RuntimeException: Don't access this client-side!
	at mcjty.lib.worlddata.AbstractWorldData.getData(AbstractWorldData.java:48) ~[AbstractWorldData.class:?]
	at mcjty.rftools.blocks.blockprotector.BlockProtectors.getProtectors(BlockProtectors.java:66) ~[BlockProtectors.class:?]
	at mcjty.rftools.blocks.blockprotector.BlockProtectors.getProtectors(BlockProtectors.java:36) ~[BlockProtectors.class:?]
	at mcjty.rftools.ForgeEventHandlers.onPlayerInteractEvent(ForgeEventHandlers.java:190) ~[ForgeEventHandlers.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1558_ForgeEventHandlers_onPlayerInteractEvent_PlayerInteractEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1125) ~[ForgeHooks.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:398) ~[bsa.class:?]
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1577) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2252) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]`

**Comment by ivanpopelyshev** [comment]
It also appears when I access rftools dimensions.

```
[main/FATAL] [net.minecraft.client.Minecraft]: Unreported exception thrown!
java.lang.RuntimeException: Don't access this client-side!
    at mcjty.lib.worlddata.AbstractWorldData.getData(AbstractWorldData.java:48) ~[AbstractWorldData.class:?]
    at mcjty.rftoolsdim.dimensions.DimensionStorage.getDimensionStorage(DimensionStorage.java:30) ~[DimensionStorage.class:?]
```

**Comment by manimax3** [comment]
Having the same issues. But I got it working by changing line 48 in AbstractWorldData.java instead of throwing an exception, returning null (I know it's not properly fixing the underlying issue ^^). Been playing for a couple of hours and everything seems to work now.

**Comment by MasterEnderman** [comment]
Already fixed in the next release:
https://github.com/McJtyMods/RFTools/issues/1768
