### ISSUE TITLE
Crash with MCJTYLIB 3.0.0 (not enough wands)

### ISSUE THREAD

**Issue by Knito58** [McJty/McJtyLib#80]
... after updating RFTools, Xnet and Mcjtylib. Seems we forgot about "Not enough wands".

Time: 6/5/18 8:21 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Not Enough Wands (notenoughwands)
Caused by: java.lang.NoSuchMethodError: mcjty.lib.network.PacketHandler.nextID()I
	at romelo333.notenoughwands.network.NEWPacketHandler.registerMessages(NEWPacketHandler.java:15)
	at romelo333.notenoughwands.proxy.CommonProxy.preInit(CommonProxy.java:30)
	at romelo333.notenoughwands.proxy.ClientProxy.preInit(ClientProxy.java:25)
	at romelo333.notenoughwands.NotEnoughWands.preInit(NotEnoughWands.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
....

**Comment by McJty** [comment]
Well you have to update that mod too

**Comment by Knito58** [comment]
Aaaarggggh.... Close this please!

**Comment by Knito58** [comment]
... for some reason this mod was not in curseforge's notification list.
